---
- name: "tmos.main: gather facts"
  bigip_facts:
    server: "{{ ansible_host | default(inventory_hostname) }}"
    include: "{{ _network_facts_gather_subset }}"
  register: "r_platform_facts"

- name: "tmos.main: set facts under ansible_facts"
  set_fact:
    ansible_facts: "r_platform_facts"
