---
- name: "cnos.main: gather facts"
  cnos_facts:
    gather_subset: "{{ _network_facts_gather_subset }}"
  register: "r_platform_facts"

- name: "cnos.main: set facts under ansible_facts"
  set_fact:
    ansible_facts: "r_platform_facts"
